trigger:
- '*'

variables:
  buildConfiguration: 'Release'

pool:
  name: NameOfYourPool
  demands:
   - agent.name -equals DESKTOP-A2V09LL

stages:
- stage: 'Build'
  displayName: 'Build the web application'

  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-20.04'
      demands:
      - npm

    variables:
      wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
      dotnetSdkVersion: '6.x'

    steps:
    - task: AzureRmWebAppDeployment@5
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure para estudiantes: Starter(3ad58780-797f-4bc4-82a4-ef66cbb5ba92)'
        appType: 'webApp'
        WebAppName: 'tailspint'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'