trigger:
- '*'
pool:
  name: Default
  demands:
   - agent.name -equals DESKTOP-A2V09LL

variables:
  buildConfiguration: 'Release'

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  pool:
    name: Default
    demands:
     - agent.name -equals DESKTOP-A2V09LL

  jobs: 
  - job: 'Build'
    displayName: 'Build job'

    variables:
      wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
      dotnetSdkVersion: '6.x'

    steps:
    - task: AzureRmWebAppDeployment@5
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure para estudiantes: Starter(3ad58780-797f-4bc4-82a4-ef66cbb5ba92)'
        appType: 'webApp'
        WebAppName: 'tailspint'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'